workflows:
  android-apk-only:
    name: Android APK Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: "3.19.6"
      xcode: false
      java: 11
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Clean and get packages
        script: |
          flutter clean
          flutter pub get
          flutter doctor
      - name: Set version name and code from Git
        script: |
          VERSION_NAME=$(git describe --tags --always)
          VERSION_CODE=$(git rev-list --count HEAD)
          echo "Version: $VERSION_NAME ($VERSION_CODE)"
          flutter build apk --release \
            --build-name=$VERSION_NAME \
            --build-number=$VERSION_CODE
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - captionjacksparrow192@gmail.com
        notify:
          success: true
          failure: true
