name: habitune
description: A comprehensive habit tracking application that adapts to user needs through thoughtful design.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  uuid: ^3.0.7
  path_provider: ^2.0.15
  flutter_svg: ^2.0.5
  table_calendar: ^3.0.9
  fl_chart: ^0.62.0
  shared_preferences: ^2.1.1
  flutter_local_notifications: ^14.1.1
  permission_handler: ^10.2.0
  device_info_plus: ^9.0.2
  package_info_plus: ^4.0.2
  firebase_core: ^2.13.1
  firebase_analytics: ^10.4.2
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  bloc_test: ^9.1.1
  mockito: ^5.4.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/app_icon.svg
    - assets/images/splash_screen.svg
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.svg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.svg"

flutter_native_splash:
  color: "#673AB7"
  image: assets/images/splash_screen.svg
  android: true
  ios: true
